services:
  mlflow:
    build: .
    container_name: loan-mlops-mlflow
    working_dir: /app
    environment:
      PYTHONPATH: /app/src
    command:
      [
      "mlflow",
      "server",
      "--host", "0.0.0.0",
      "--port", "5000",
      "--backend-store-uri", "sqlite:////mlflow/mlflow.db",
      "--artifacts-destination", "/mlflow/artifacts",
      "--serve-artifacts",
      "--allowed-hosts", "*"
      ]
    ports:
      - "5001:5000"
    volumes:
      - .:/app
      - mlflow_data:/mlflow
    healthcheck:
      test: ["CMD", "python", "-c", "import socket; s=socket.create_connection(('127.0.0.1', 5000), 2); s.close()"]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 10s
    restart: unless-stopped

  api:
    build: .
    container_name: loan-mlops-api
    working_dir: /app
    depends_on:
      mlflow:
        condition: service_healthy
    environment:
      PYTHONPATH: /app/src
      MLFLOW_TRACKING_URI: http://mlflow:5000
      MLFLOW_EXPERIMENT_NAME: Loan Default Prediction
      MLFLOW_MODEL_NAME: loan_default_predictor
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    restart: unless-stopped

  streamlit:
      build: .
      container_name: loan-mlops-streamlit
      working_dir: /app
      depends_on:
        api:
          condition: service_started
      environment:
        PYTHONPATH: /app/src
        LOAN_API_URL: http://api:8000
      command: streamlit run streamlit_app.py --server.address 0.0.0.0 --server.port 8501
      ports:
        - "8501:8501"
      volumes:
        - .:/app
      restart: unless-stopped

volumes:
  mlflow_data: